org.gradle.jvmargs=-Xmx4G
android.useAndroidX=true
android.enableJetifier=true
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
android.builtInKotlin=false
