import 'package:get/get_rx/src/rx_types/rx_types.dart';
import 'package:jd_flutter/bean/http/response/attendance_dashboard_info.dart';

class AttendanceDashboardState {
  var json = [
    {
      "factory": "Gold Emperor (BD) Limited",
      "departmentCode": "60.01",
      "departmentName": "BD. General Manager Office 孟加拉_总经办",
      "totalEmployees": 3,
      "attendanceCount": 3,
      "absenceCount": 0,
      "lateOrEarlyCount": 0,
      "publicHoliday": 0.0,
      "legalHolidays": 0.0,
      "yearRest": 0.0,
      "absenceRate": "0%",
      "leaveTotal": 0.0,
      "casualLeave": 0.0,
      "sickLeave": 0.0,
      "workInjury": 0.0,
      "maternityLeave": 0.0,
      "marriageLeave": 0.0,
      "funeralLeave": 0.0
    },
    {
      "factory": "Gold Emperor (BD) Limited",
      "departmentCode": "60.02.01",
      "departmentName": "BD. Inlet group",
      "totalEmployees": 1,
      "attendanceCount": 1,
      "absenceCount": 0,
      "lateOrEarlyCount": 0,
      "publicHoliday": 0.0,
      "legalHolidays": 0.0,
      "yearRest": 0.0,
      "absenceRate": "0%",
      "leaveTotal": 0.0,
      "casualLeave": 0.0,
      "sickLeave": 0.0,
      "workInjury": 0.0,
      "maternityLeave": 0.0,
      "marriageLeave": 0.0,
      "funeralLeave": 0.0
    },
    {
      "factory": "Gold Emperor (BD) Limited",
      "departmentCode": "60.03",
      "departmentName": "BD. HR & Admin Dept 孟加拉_人力行政部",
      "totalEmployees": 2,
      "attendanceCount": 2,
      "absenceCount": 0,
      "lateOrEarlyCount": 0,
      "publicHoliday": 0.0,
      "legalHolidays": 0.0,
      "yearRest": 0.0,
      "absenceRate": "0%",
      "leaveTotal": 0.0,
      "casualLeave": 0.0,
      "sickLeave": 0.0,
      "workInjury": 0.0,
      "maternityLeave": 0.0,
      "marriageLeave": 0.0,
      "funeralLeave": 0.0
    },
    {
      "factory": "Gold Emperor (BD) Limited",
      "departmentCode": "60.03.01",
      "departmentName": "BD. HR Operation Course",
      "totalEmployees": 2,
      "attendanceCount": 2,
      "absenceCount": 0,
      "lateOrEarlyCount": 0,
      "publicHoliday": 0.0,
      "legalHolidays": 0.0,
      "yearRest": 0.0,
      "absenceRate": "0%",
      "leaveTotal": 0.0,
      "casualLeave": 0.0,
      "sickLeave": 0.0,
      "workInjury": 0.0,
      "maternityLeave": 0.0,
      "marriageLeave": 0.0,
      "funeralLeave": 0.0
    },
    {
      "factory": "Gold Emperor (BD) Limited",
      "departmentCode": "60.03.02",
      "departmentName": "BD. Administration Course",
      "totalEmployees": 8,
      "attendanceCount": 7,
      "absenceCount": 1,
      "lateOrEarlyCount": 3,
      "publicHoliday": 0.0,
      "legalHolidays": 0.0,
      "yearRest": 0.0,
      "absenceRate": "13%",
      "leaveTotal": 0.0,
      "casualLeave": 0.0,
      "sickLeave": 0.0,
      "workInjury": 0.0,
      "maternityLeave": 0.0,
      "marriageLeave": 0.0,
      "funeralLeave": 0.0
    },
    {
      "factory": "Gold Emperor (BD) Limited",
      "departmentCode": "60.05",
      "departmentName": "BD. Storage Dept. 孟加拉_仓储部",
      "totalEmployees": 10,
      "attendanceCount": 10,
      "absenceCount": 0,
      "lateOrEarlyCount": 1,
      "publicHoliday": 0.0,
      "legalHolidays": 0.0,
      "yearRest": 0.0,
      "absenceRate": "0%",
      "leaveTotal": 0.0,
      "casualLeave": 0.0,
      "sickLeave": 0.0,
      "workInjury": 0.0,
      "maternityLeave": 0.0,
      "marriageLeave": 0.0,
      "funeralLeave": 0.0
    },
    {
      "factory": "Gold Emperor (BD) Limited",
      "departmentCode": "60.06",
      "departmentName": "BD. PMC Dept 孟加拉_生管部",
      "totalEmployees": 8,
      "attendanceCount": 8,
      "absenceCount": 0,
      "lateOrEarlyCount": 2,
      "publicHoliday": 0.0,
      "legalHolidays": 0.0,
      "yearRest": 0.0,
      "absenceRate": "0%",
      "leaveTotal": 0.0,
      "casualLeave": 0.0,
      "sickLeave": 0.0,
      "workInjury": 0.0,
      "maternityLeave": 0.0,
      "marriageLeave": 0.0,
      "funeralLeave": 0.0
    },
    {
      "factory": "Gold Emperor (BD) Limited",
      "departmentCode": "60.07",
      "departmentName": "BD. QC Dept. 孟加拉_品质部",
      "totalEmployees": 16,
      "attendanceCount": 15,
      "absenceCount": 1,
      "lateOrEarlyCount": 6,
      "publicHoliday": 0.0,
      "legalHolidays": 0.0,
      "yearRest": 0.0,
      "absenceRate": "6%",
      "leaveTotal": 0.0,
      "casualLeave": 0.0,
      "sickLeave": 0.0,
      "workInjury": 0.0,
      "maternityLeave": 0.0,
      "marriageLeave": 0.0,
      "funeralLeave": 0.0
    },
    {
      "factory": "Gold Emperor (BD) Limited",
      "departmentCode": "60.08.01",
      "departmentName": "BD. Laminating Line",
      "totalEmployees": 6,
      "attendanceCount": 6,
      "absenceCount": 0,
      "lateOrEarlyCount": 1,
      "publicHoliday": 0.0,
      "legalHolidays": 0.0,
      "yearRest": 0.0,
      "absenceRate": "0%",
      "leaveTotal": 0.0,
      "casualLeave": 0.0,
      "sickLeave": 0.0,
      "workInjury": 0.0,
      "maternityLeave": 0.0,
      "marriageLeave": 0.0,
      "funeralLeave": 0.0
    },
    {
      "factory": "Gold Emperor (BD) Limited",
      "departmentCode": "60.08.03.01",
      "departmentName": "BD. Cutting Line 1",
      "totalEmployees": 36,
      "attendanceCount": 32,
      "absenceCount": 4,
      "lateOrEarlyCount": 2,
      "publicHoliday": 0.0,
      "legalHolidays": 0.0,
      "yearRest": 0.0,
      "absenceRate": "11%",
      "leaveTotal": 0.0,
      "casualLeave": 0.0,
      "sickLeave": 0.0,
      "workInjury": 0.0,
      "maternityLeave": 0.0,
      "marriageLeave": 0.0,
      "funeralLeave": 0.0
    },
    {
      "factory": "Gold Emperor (BD) Limited",
      "departmentCode": "60.08.04.02",
      "departmentName": "BD. Sewing Dept. Class I 针车1课",
      "totalEmployees": 6,
      "attendanceCount": 4,
      "absenceCount": 2,
      "lateOrEarlyCount": 0,
      "publicHoliday": 0.0,
      "legalHolidays": 0.0,
      "yearRest": 0.0,
      "absenceRate": "33%",
      "leaveTotal": 0.0,
      "casualLeave": 0.0,
      "sickLeave": 0.0,
      "workInjury": 0.0,
      "maternityLeave": 0.0,
      "marriageLeave": 0.0,
      "funeralLeave": 0.0
    },
    {
      "factory": "Gold Emperor (BD) Limited",
      "departmentCode": "60.08.04.02.01",
      "departmentName": "BD. Sewing Line 1",
      "totalEmployees": 120,
      "attendanceCount": 102,
      "absenceCount": 18,
      "lateOrEarlyCount": 2,
      "publicHoliday": 0.0,
      "legalHolidays": 0.0,
      "yearRest": 0.0,
      "absenceRate": "15%",
      "leaveTotal": 0.0,
      "casualLeave": 0.0,
      "sickLeave": 0.0,
      "workInjury": 0.0,
      "maternityLeave": 0.0,
      "marriageLeave": 0.0,
      "funeralLeave": 0.0
    },
    {
      "factory": "Gold Emperor (BD) Limited",
      "departmentCode": "60.08.04.02.02",
      "departmentName": "BD. Sewing Line 2",
      "totalEmployees": 18,
      "attendanceCount": 14,
      "absenceCount": 4,
      "lateOrEarlyCount": 0,
      "publicHoliday": 0.0,
      "legalHolidays": 0.0,
      "yearRest": 0.0,
      "absenceRate": "22%",
      "leaveTotal": 0.0,
      "casualLeave": 0.0,
      "sickLeave": 0.0,
      "workInjury": 0.0,
      "maternityLeave": 0.0,
      "marriageLeave": 0.0,
      "funeralLeave": 0.0
    },
    {
      "factory": "Gold Emperor (BD) Limited",
      "departmentCode": "60.08.04.05",
      "departmentName": "BD. Sewing Supporting",
      "totalEmployees": 1,
      "attendanceCount": 1,
      "absenceCount": 0,
      "lateOrEarlyCount": 0,
      "publicHoliday": 0.0,
      "legalHolidays": 0.0,
      "yearRest": 0.0,
      "absenceRate": "0%",
      "leaveTotal": 0.0,
      "casualLeave": 0.0,
      "sickLeave": 0.0,
      "workInjury": 0.0,
      "maternityLeave": 0.0,
      "marriageLeave": 0.0,
      "funeralLeave": 0.0
    },
    {
      "factory": "Gold Emperor (BD) Limited",
      "departmentCode": "60.08.05.01",
      "departmentName": "BD. Lasting Dept. Class I 成型1课",
      "totalEmployees": 21,
      "attendanceCount": 18,
      "absenceCount": 3,
      "lateOrEarlyCount": 15,
      "publicHoliday": 0.0,
      "legalHolidays": 0.0,
      "yearRest": 0.0,
      "absenceRate": "14%",
      "leaveTotal": 0.0,
      "casualLeave": 0.0,
      "sickLeave": 0.0,
      "workInjury": 0.0,
      "maternityLeave": 0.0,
      "marriageLeave": 0.0,
      "funeralLeave": 0.0
    },
    {
      "factory": "Gold Emperor (BD) Limited",
      "departmentCode": "60.08.05.01.01",
      "departmentName": "BD. Lasting Line 1 成型1线",
      "totalEmployees": 64,
      "attendanceCount": 57,
      "absenceCount": 7,
      "lateOrEarlyCount": 47,
      "publicHoliday": 0.0,
      "legalHolidays": 0.0,
      "yearRest": 0.0,
      "absenceRate": "11%",
      "leaveTotal": 0.0,
      "casualLeave": 0.0,
      "sickLeave": 0.0,
      "workInjury": 0.0,
      "maternityLeave": 0.0,
      "marriageLeave": 0.0,
      "funeralLeave": 0.0
    },
    {
      "factory": "Gold Emperor (BD) Limited",
      "departmentCode": "60.08.05.01.01.01",
      "departmentName": "BD. Lasting Line 1 Front",
      "totalEmployees": 2,
      "attendanceCount": 2,
      "absenceCount": 0,
      "lateOrEarlyCount": 2,
      "publicHoliday": 0.0,
      "legalHolidays": 0.0,
      "yearRest": 0.0,
      "absenceRate": "0%",
      "leaveTotal": 0.0,
      "casualLeave": 0.0,
      "sickLeave": 0.0,
      "workInjury": 0.0,
      "maternityLeave": 0.0,
      "marriageLeave": 0.0,
      "funeralLeave": 0.0
    },
    {
      "factory": "Gold Emperor (BD) Limited",
      "departmentCode": "60.08.05.01.02",
      "departmentName": "BD. Lasting Line 2 成型2线",
      "totalEmployees": 11,
      "attendanceCount": 10,
      "absenceCount": 1,
      "lateOrEarlyCount": 5,
      "publicHoliday": 0.0,
      "legalHolidays": 0.0,
      "yearRest": 0.0,
      "absenceRate": "9%",
      "leaveTotal": 0.0,
      "casualLeave": 0.0,
      "sickLeave": 0.0,
      "workInjury": 0.0,
      "maternityLeave": 0.0,
      "marriageLeave": 0.0,
      "funeralLeave": 0.0
    },
    {
      "factory": "Gold Emperor (BD) Limited",
      "departmentCode": "60.08.05.02.01.01",
      "departmentName": "BD. Lasting Line 3 Front",
      "totalEmployees": 1,
      "attendanceCount": 1,
      "absenceCount": 0,
      "lateOrEarlyCount": 0,
      "publicHoliday": 0.0,
      "legalHolidays": 0.0,
      "yearRest": 0.0,
      "absenceRate": "0%",
      "leaveTotal": 0.0,
      "casualLeave": 0.0,
      "sickLeave": 0.0,
      "workInjury": 0.0,
      "maternityLeave": 0.0,
      "marriageLeave": 0.0,
      "funeralLeave": 0.0
    },
    {
      "factory": "Gold Emperor (BD) Limited",
      "departmentCode": "60.08.05.03",
      "departmentName": "BD. OutSole Dept.孟加拉_包跟课",
      "totalEmployees": 44,
      "attendanceCount": 39,
      "absenceCount": 5,
      "lateOrEarlyCount": 12,
      "publicHoliday": 0.0,
      "legalHolidays": 0.0,
      "yearRest": 0.0,
      "absenceRate": "11%",
      "leaveTotal": 0.0,
      "casualLeave": 0.0,
      "sickLeave": 0.0,
      "workInjury": 0.0,
      "maternityLeave": 0.0,
      "marriageLeave": 0.0,
      "funeralLeave": 0.0
    },
    {
      "factory": "Gold Emperor (BD) Limited",
      "departmentCode": "60.08.05.04",
      "departmentName": "BD. Lasting Supporting",
      "totalEmployees": 1,
      "attendanceCount": 1,
      "absenceCount": 0,
      "lateOrEarlyCount": 1,
      "publicHoliday": 0.0,
      "legalHolidays": 0.0,
      "yearRest": 0.0,
      "absenceRate": "0%",
      "leaveTotal": 0.0,
      "casualLeave": 0.0,
      "sickLeave": 0.0,
      "workInjury": 0.0,
      "maternityLeave": 0.0,
      "marriageLeave": 0.0,
      "funeralLeave": 0.0
    },
    {
      "factory": "Gold Emperor (BD) Limited",
      "departmentCode": "60.09",
      "departmentName": "BD. Equipment engineering class 孟加拉_设备工程课",
      "totalEmployees": 3,
      "attendanceCount": 3,
      "absenceCount": 0,
      "lateOrEarlyCount": 0,
      "publicHoliday": 0.0,
      "legalHolidays": 0.0,
      "yearRest": 0.0,
      "absenceRate": "0%",
      "leaveTotal": 0.0,
      "casualLeave": 0.0,
      "sickLeave": 0.0,
      "workInjury": 0.0,
      "maternityLeave": 0.0,
      "marriageLeave": 0.0,
      "funeralLeave": 0.0
    },
    {
      "factory": "Gold Emperor (BD) Limited",
      "departmentCode": "60.10",
      "departmentName": "BD. Pengontrolan Costing 孟加拉_成控部",
      "totalEmployees": 2,
      "attendanceCount": 2,
      "absenceCount": 0,
      "lateOrEarlyCount": 0,
      "publicHoliday": 0.0,
      "legalHolidays": 0.0,
      "yearRest": 0.0,
      "absenceRate": "0%",
      "leaveTotal": 0.0,
      "casualLeave": 0.0,
      "sickLeave": 0.0,
      "workInjury": 0.0,
      "maternityLeave": 0.0,
      "marriageLeave": 0.0,
      "funeralLeave": 0.0
    },
    {
      "factory": "Gold Emperor (BD) Limited",
      "departmentCode": "60.11.01",
      "departmentName": "BD. Accountant Course",
      "totalEmployees": 1,
      "attendanceCount": 1,
      "absenceCount": 0,
      "lateOrEarlyCount": 0,
      "publicHoliday": 0.0,
      "legalHolidays": 0.0,
      "yearRest": 0.0,
      "absenceRate": "0%",
      "leaveTotal": 0.0,
      "casualLeave": 0.0,
      "sickLeave": 0.0,
      "workInjury": 0.0,
      "maternityLeave": 0.0,
      "marriageLeave": 0.0,
      "funeralLeave": 0.0
    },
    {
      "factory": "Gold Emperor (BD) Limited",
      "departmentCode": "60.12",
      "departmentName": "BD. Purchasing Dept. 孟加拉_采购部",
      "totalEmployees": 1,
      "attendanceCount": 1,
      "absenceCount": 0,
      "lateOrEarlyCount": 0,
      "publicHoliday": 0.0,
      "legalHolidays": 0.0,
      "yearRest": 0.0,
      "absenceRate": "0%",
      "leaveTotal": 0.0,
      "casualLeave": 0.0,
      "sickLeave": 0.0,
      "workInjury": 0.0,
      "maternityLeave": 0.0,
      "marriageLeave": 0.0,
      "funeralLeave": 0.0
    }
  ];
  var attendanceDataList = <AttendanceDashboardInfo>[].obs;

  AttendanceDashboardState() {
    attendanceDataList.value =
        json.map((v) => AttendanceDashboardInfo.fromJson(v)).toList();
  }
}
